/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f407xx.h"

#define BV(n) (1 << (n))

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define LED_GREEN   12
#define LED_ORANGE  13
#define LED_RED     14
#define LED_BLUE    15

#define ALL_LEDS    (BV(12) | BV(13) | BV(14) | BV(15))
#define PAIR1       (BV(12) | BV(14))
#define PAIR2       (BV(13) | BV(15))

void led_init(void);
void led_on(void);
void led_off(void);
void led_on_q1(void);
void led_off_q1(void);
void led_alternate_pattern1(void);
void led_alternate_pattern2(void);
void led_run_lr(void);
void led_run_rl(void);
void led_toggle_xor(void);
void pattern_transition(void);

const uint8_t led_pins[4] = {LED_GREEN, LED_ORANGE, LED_RED, LED_BLUE};

int main(void)
{
    led_init();
    uint8_t i;

    while(1)
    {
        // Q1: Single LED Blink (PD12 only)
        for(i = 0; i < 3; i++)
        {
            led_on_q1();
            DelayMs(200);
            led_off_q1();
            DelayMs(200);
        }
        pattern_transition();

        // Q2: Alternate LED Blink
        for(i = 0; i < 3; i++)
        {
            led_alternate_pattern1();
            DelayMs(200);
            led_alternate_pattern2();
            DelayMs(200);
        }
        pattern_transition();

        // Q3: Running LED Left to Right
        for(i = 0; i < 2; i++)
        {
            led_run_lr();
        }
        pattern_transition();

        // Q4: Running LED Right to Left
        for(i = 0; i < 2; i++)
        {
            led_run_rl();
        }
        pattern_transition();

        // Q5: All LEDs Blink Together
        for(i = 0; i < 4; i++)
        {
            led_on();
            DelayMs(150);
            led_off();
            DelayMs(150);
        }
        pattern_transition();

        // Q6: LED Toggle with XOR
        for(i = 0; i < 6; i++)
        {
            led_toggle_xor();
            DelayMs(200);
        }
        pattern_transition();
    }
}

void led_init(void)
{
    RCC->AHB1ENR |= BV(3);

    GPIOD->MODER &= ~(BV(25) | BV(27) | BV(29) | BV(31));
    GPIOD->MODER |= BV(24) | BV(26) | BV(28) | BV(30);

    GPIOD->OTYPER &= ~(BV(12) | BV(13) | BV(14) | BV(15));

    GPIOD->OSPEEDR &= ~(BV(25) | BV(27) | BV(29) | BV(31));
    GPIOD->OSPEEDR &= ~(BV(24) | BV(26) | BV(28) | BV(30));

    GPIOD->PUPDR &= ~(BV(25) | BV(27) | BV(29) | BV(31));
    GPIOD->PUPDR &= ~(BV(24) | BV(26) | BV(28) | BV(30));
}

// Q1: Single LED
void led_on_q1(void)
{
    GPIOD->ODR |= BV(12);
}

void led_off_q1(void)
{
    GPIOD->ODR &= ~BV(12);
}

// Q2: Alternate
void led_alternate_pattern1(void)
{
    GPIOD->ODR &= ~ALL_LEDS;
    GPIOD->ODR |= PAIR1;
}

void led_alternate_pattern2(void)
{
    GPIOD->ODR &= ~ALL_LEDS;
    GPIOD->ODR |= PAIR2;
}

// Q3: Left to Right
void led_run_lr(void)
{
    uint8_t i;
    for(i = 0; i < 4; i++)
    {
        GPIOD->ODR &= ~ALL_LEDS;
        GPIOD->ODR |= BV(led_pins[i]);
        DelayMs(150);
    }
}

// Q4: Right to Left
void led_run_rl(void)
{
    int8_t i;
    for(i = 3; i >= 0; i--)
    {
        GPIOD->ODR &= ~ALL_LEDS;
        GPIOD->ODR |= BV(led_pins[i]);
        DelayMs(150);
    }
}

// Q5: All LEDs
void led_on(void)
{
    GPIOD->ODR |= ALL_LEDS;
}

void led_off(void)
{
    GPIOD->ODR &= ~ALL_LEDS;
}

// Q6: XOR Toggle
void led_toggle_xor(void)
{
    GPIOD->ODR ^= ALL_LEDS;
}

// Transition between patterns
void pattern_transition(void)
{
    GPIOD->ODR &= ~ALL_LEDS;
    DelayMs(100);
}
